Features into main
Have-Samuel/testing pull request #1
Opened 2021-11-23 20:55 UTC by Have-Samuel

Touching HTML, CSS and GitHub

2021-11-23 22:20 UTC, mmsesay requested changes
Hi @Have-Samuel , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- A PR with a short summary describing what you worked on.
    *Example: In this PR I setup linters, add HTML and CSS files etc*

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 22:20 UTC, mmsesay commented on README.md
> +### Deployment -GitHub
- [ ] [OPTIONAL] Good job in working on the README :clap:  On future projects,  you can try to add sections that are applicable to your project.

2021-11-23 22:20 UTC, mmsesay commented on .gitignore
> +test.md
- [ ] It's good you added the `test.md` in the gitignore file. But the file is still present in your repository.
You can try to clear the cache, stage, commit and push again. Please take a look at this [blog](https://bytefreaks.net/programming-2/my-gitignore-file-is-ignored-by-git-and-it-does-not-work) for a way around.

2021-11-23 22:53 UTC, Have-Samuel commented on README.md
> +### Deployment -GitHub
Thank you for the advise and the comments.

2021-11-24 00:33 UTC, Cathella approved these changes
## Hi @Have-Samuel 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Suggestions
_I recommend that you take a look at the comments below that suggest optional requirements that would be good to implement to make your look more professional._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 00:33 UTC, Cathella commented on README.md
> +### Deployment -GitHub
- [ ] [Optional] For a more professional README file, I suggest that you delete the highlighted section because it does not describe anything related to this project

2021-11-24 00:33 UTC, Cathella commented on index.css
> +}
- [ ] [Optional] This is a good choice of a selector that you used, however we can make it better by directly using `h1` as a selector. This option would look more descriptive and semantic.
```
h1 {
  color: blue;
}
```

2021-11-24 01:16 UTC, merged